### ISSUE TITLE
Log Browser (ctrl-f for digging in the underlying data)

### ISSUE THREAD

**Issue by Smogard49** [Geigerkind/LegacyPlayersV3#114]
Finding things such as damage ranges for spells on p-servers or trying to figure out if a server has working mechanics is one of the big hurdles to some speccs with intricate interactions, likewise trying to figure out who in the raid failed on a essential mechanic leading to that wipe on vashj when you were pushing for a new speedclear;

WoL has this feature called "Log Query" which essentially queries the underlying data akin to ctrl-f showing you that timestamp of when someone used the vashj core or similar, example below for querying all of Tusses drain souls and corruptions on Sunceds Twin Valks 3:30 kill on Frosthold while only showing the drain soul query; 
![image](https://user-images.githubusercontent.com/18141710/90329990-c5401600-dfa9-11ea-855d-9e92804b6ab7.png)

Now, there are plenty of ways to implementing such a feature and the querry builder on WoL is in no way unique or in any way special; likewise while being able to download the underlying logs and doing it manually would work with any code-analyzartion software, this is a handy and quick solution that efficiently brings you the timestamps and number's you're searching for. Querry Builder on WoL used as example: 
![image](https://user-images.githubusercontent.com/18141710/90330221-6a0f2300-dfab-11ea-9710-70be1c636a60.png)

This is a tertiary structure most likely; but one that will be needed if the goal is to dethrone WoL for Wrath. WoL is in no way a perfect log browser, but it does a decent enough job on almost every front such that simply surpassing it in the most basic aspects wont validate a change to a less useful tool when it comes to actually relying on it to find and fix raid(ing) issues.

**Comment by Geigerkind** [comment]
Some thoughts:
* Query (Overwrite flag?) at the filter menu
* SQL like syntax with autocomplete, e.g. select melee_damage, aura_application where attempt in (freya1, freya2) and source in (bla) and ability in (bla)
* We need a guide explaining the syntax
* A view to see all current combat events

**Comment by Geigerkind** [comment]
Took a while but a similar feature has now been implemented.
Please check it out and give feedback :)
