### ISSUE TITLE
Consumes missing from source aura uptime

### ISSUE THREAD

**Issue by fluffyst** [Geigerkind/LegacyPlayersV3#127]
I think consumes are missing from "source aura uptime" in v3

Can see on v2, you can see Well Fed and Supreme Power on fluffys, can't see it at all in v3.
https://legacyplayers.com/Raids/Viewer/Default.aspx?id=13754&exp=1&upl=21176
https://alpha.legacyplayers.com/viewer/27/ability

**Comment by Geigerkind** [comment]
Fixed
