### ISSUE TITLE
API rankings/character/ => Add raid ID

### ISSUE THREAD

**Issue by brz-admin** [Geigerkind/LegacyPlayersV3#158]
When asking the api for https://alpha.legacyplayers.com/API/instance/ranking/character/{characters_id} getting the raid ID would be great to link the record to a raid report.

**Comment by brz-admin** [comment]
Also, it would be nice to have server_wise ranking of the player for that encounter

**Comment by Geigerkind** [comment]
Added `instance_meta_id` which is the primary key for the raid
