### ISSUE TITLE
Loot not shown correctly when i uploaded raidlogs

### ISSUE THREAD

**Issue by MythiixLtd** [Geigerkind/LegacyPlayersV3#162]
**Describe the bug**
When i ulpoaded my raidlog from ulduar today i saw the loot from the boss but it only showed the emblems

**To Reproduce**
Just upload any raidlog that had items drop from bosses should do it i think

**Expected behavior**
You should be able to see dropped item and emblems and who they went to

[Uld10.zip](https://github.com/Geigerkind/LegacyPlayersV3/files/6200895/Uld10.zip)

**Comment by Geigerkind** [comment]
I fixed a loot related issue in the Frontend.
A further update to loot accuracy will come with a later feature.
