### ISSUE TITLE
Logs - Update URL when filtering

### ISSUE THREAD

**Issue by kloze1** [Geigerkind/LegacyPlayersV3#164]
**Is your feature request related to a problem? Please describe.**
Trouble linking and going back after apply some filters, doesn't always work.

**Describe the solution you'd like**
Every time you apply a filter, update the URL.  You can always link to exactly what you're looking at and use the back button to undo filters.

**Describe alternatives you've considered**

**Additional context**
Website like warcraft logs and mint.com update the URL in this fashion.

**Comment by Geigerkind** [comment]
You can click on the "Share" button to share the URL.
Besides that filter that you apply should work with your history buttons.

**Comment by Geigerkind** [comment]
Closing this, as this is already implemented in another fassion.
