### ISSUE TITLE
Show graph + table/bar view by default and allow for zooming

### ISSUE THREAD

**Issue by kloze1** [Geigerkind/LegacyPlayersV3#165]
**Is your feature request related to a problem? Please describe.**
I like to zoom in on specific sections of the log to look at high damage taken, high damage done, see lust, etc.

**Describe the solution you'd like**
Shows both tables/bars and the graph above.  If a specific region is selected, update both graph and table for that timeframe.

**Describe alternatives you've considered**
None.

**Additional context**
Main View (from WCL):
![main view](https://user-images.githubusercontent.com/75041220/113900756-c66dbf80-9793-11eb-8406-38c0dcde651d.PNG)

Zoom view (from WCL):
![zoom_view](https://user-images.githubusercontent.com/75041220/113900781-cec5fa80-9793-11eb-9d63-1069e5ab551e.PNG)

**Comment by Geigerkind** [comment]
I think I implemented this.
