### ISSUE TITLE
Allow users to filter by time

### ISSUE THREAD

**Issue by nikko8085** [Geigerkind/LegacyPlayersV3#167]
Allowing the users to filter by time within a fight allows the user to examine in detail what happened at a sub-set of the fight. This can be for example looking at the 20 seconds leading up to a tank death, or wanting to see DPS done during a weakness phase, etc.

Like in the old version, you could filter by time by having a window for start time and end time.

I don't think there are any good alternatives to this option

I know other users have been asking for this on Discord too.

**Comment by Geigerkind** [comment]
Implemented.
Specific Time filtering will be implemented in the advanced query feature.
