### ISSUE TITLE
Incomplete boss segments when encounter start with adds

### ISSUE THREAD

**Issue by marsbob-dev** [Geigerkind/LegacyPlayersV3#168]
**Describe the bug**
As I told you on discord, every boss encounter starting with adds are incomplete. 
Legacy split adds and boss parts.
EDIT: on wow 1.12.1 @Nostalgeek

**To Reproduce**
1. Go to: https://alpha.legacyplayers.com/viewer/2542/base
2. Click on: heigan or KT segments 
3. Scroll down to: trash part, you can easily see the adds part of those fights are consider as a raid trash

**Expected behavior**
Adds part have to be merged automaticly with boss segments

**Comment by Geigerkind** [comment]
Should work now.
