### ISSUE TITLE
Guild name does not appear on legacy raid list

### ISSUE THREAD

**Issue by marsbob-dev** [Geigerkind/LegacyPlayersV3#169]
**Describe the bug**
wow 1.12.1 @nostalgeek
All Naxxramas runs appears as "PUG raid" instead of showing the correct guid name

**To Reproduce**
1. Go to: https://alpha.legacyplayers.com/pve
2. Go @ page 6 (4 runs @Nostalgeek, all PUG raid)

**Expected behavior**
Guild name should appears

**Comment by Geigerkind** [comment]
Relates to https://github.com/Geigerkind/LegacyPlayersV3/issues/171
