### ISSUE TITLE
Attempts dropdown should only show applicable fights

### ISSUE THREAD

**Issue by oli356** [Geigerkind/LegacyPlayersV3#218]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When you select a boss in the upper checkboxes, for example 'Rotface', I would like it so in the lower box, only the Rotface attempts are shown and all other bosses are not.
![image](https://user-images.githubusercontent.com/38960533/120707391-29d54e80-c4b2-11eb-9898-14fc0e03e194.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Geigerkind** [comment]
Hi. There used to be such a feature. But the community did not like it.
I cant support two contradicting ways.
I suggest you use the search bar to specifically filter out the rest?

The upper boxes are meant as shortcut to select everything.

**Comment by Geigerkind** [comment]
Will close this then. Please write in this ticket if u disagree.

**Comment by oli356** [comment]
I disagree as it seems like it should be a subfilter, but i understand you can't please everyone do its ok if people didnt like it =) 

Thanks
