### ISSUE TITLE
AdvancedWotLKCombatLog lua errors

### ISSUE THREAD

**Issue by broizter** [Geigerkind/LegacyPlayersV3#220]
I get variations of this lua error when using this addon. It also seems to disable the text in the top center of the screen where for example quest progress or text like "Trade cancelled" shows up. This particular error happened when entering Ulduar while being in a raid group.

```
Message: Interface\AddOns\AdvancedWotLKCombatLog\core.lua:341: attempt to compare number with nil
Time: 07/15/21 19:36:57
Count: 18
Stack: (tail call): ?
[C]: ?
Interface\AddOns\AdvancedWotLKCombatLog\core.lua:341: in function `?'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = "CHAT_MSG_ADDON"
(*temporary) = "RPLL_H_CBT_I_6"
(*temporary) = "0x0C0000000000643C&40395:3834:0:0:0:0:0:0:80}40350:0:0:0:0:0:0:0:80}40335:0:0:0:0:0:0:0:80}nil"
(*temporary) = "RAID"
(*temporary) = "MyCharacterName"
(*temporary) = "CHAT_MSG_ADDON"
(*temporary) = "RPLL_H_CBT_I_6"
(*temporary) = "0x0C0000000000643C&40395:3834:0:0:0:0:0:0:80}40350:0:0:0:0:0:0:0:80}40335:0:0:0:0:0:0:0:80}nil"
(*temporary) = "RAID"
(*temporary) = "MyCharacterName"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
```

**Comment by Geigerkind** [comment]
Hello @broizter , please test it with the new version (34).

**Comment by broizter** [comment]
It seems like it fixes the lua error, but the problem that the top center text stops showing wasn't fixed unfortunately. Here's a picture if the text I'm talking about. It's the same text that shows up when you kill a mob of a quest you're tracking for example.

https://i.imgur.com/hrD59Xm.png

**Comment by Geigerkind** [comment]
Hey, this is a side effect that enables the kind of logging. Im abusing this error text to write stuff into the combat log. So if I would show it you would see the rewritten error text that I write into the log.

I will close the ticket then, since the problem has been fixed.

**Comment by broizter** [comment]
That makes sense thank you! This might be the wrong place to ask, but is the addon necessary if all I want is to upload basic logs? Or is it enough to just write /combatlog in game and upload that?

**Comment by Geigerkind** [comment]
Its not necessary for wotlk, but you will see significant tracking accuracy differences.
