### ISSUE TITLE
Comprehensed Raid View

### ISSUE THREAD

**Issue by Zaorr** [Geigerkind/LegacyPlayersV3#72]
**Is your feature request related to a problem? Please describe.**
The Feature is requested for comfort and ease of use

**Describe the solution you'd like**
One Raid View, comprehensing the logs of all contributing players.

Very often, a raid has muliple players logging and contributing to legacy players. Every upload is considered as one individual "raid" entity. So e.g. Player A contributed Boss A, B and C, Player B contributed B, C and D - the comprehensed view would contain bosses A to C without the need to switch between contributors.

**Describe alternatives you've considered**

**Additional context**

**Comment by Geigerkind** [comment]
I think it is better to have one working raid view instead of multiple of the same.
This relates to improving the addon that collects data.
