### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by h3ndrk** [Geigerkind/LegacyPlayersV3#78]
**Describe the bug**
I'm getting many mails of the broken CI. Please fix that ASAP.

**To Reproduce**
1. Make a fork
2. Push commits to a branch
3. Look in your inbox

**Expected behavior**
CI does what it should do: just work.

**Screenshots**
Nope.

**Desktop (please complete the following information):**
Irrelevant.

**Smartphone (please complete the following information):**
Irrelevant.

**Additional context**
Nope.

**Comment by h3ndrk** [comment]
This issue needs to be reopened as I just received another spammy mail that the CI still doesn't work.

1. Please do not close issues that are not fixed.
2. Please do not close any issues without giving any context or reason why you think it can be closed.

Thanks!

**Comment by Geigerkind** [comment]
Maybe you should rebase the dev branch with yours

**Comment by h3ndrk** [comment]
I'm sorry, I rebased and got another mail about the broken CI.

Still not fixed, see https://github.com/h3ndrk/LegacyPlayersV3/runs/690302663.
