### ISSUE TITLE
Compile errors with rocket-multipart-form-data v0.9.2

### ISSUE THREAD

**Issue by h3ndrk** [Geigerkind/LegacyPlayersV3#80]
**Describe the bug**
The code in the current `dev`-branch does not compile anymore, when using latest dependencies from `Cargo.toml` e.g. via `cargo update`.

As a workaround, downgrading `rocket-multipart-form-data` to `v0.8.1` fixes the problem temporarily.

**To Reproduce**
1. Switch to `dev`-branch
2. Run `cargo update`
3. Run `cargo build`

**Expected behavior**
The backend should compile without compilation errors.

**Screenshots**
Here is the output of the compilation errors:

```
   Compiling backend v0.2.0 (/home/hendrik/Documents/uni/Master Semester 2 SoSe 20/Software Testing/LegacyPlayersV3/Backend)
error[E0432]: unresolved import `rocket_multipart_form_data::SingleRawField`
 --> src/modules/live_data_processor/transfer/package.rs:8:103
  |
8 | use rocket_multipart_form_data::{MultipartFormDataOptions, MultipartFormData, MultipartFormDataField, SingleRawField};
  |                                                                                                       ^^^^^^^^^^^^^^ no `SingleRawField` in the root

error[E0432]: unresolved import `rocket_multipart_form_data::RawField`
 --> src/modules/live_data_processor/transfer/package.rs:9:33
  |
9 | use rocket_multipart_form_data::RawField::Single;
  |                                 ^^^^^^^^ `RawField` is a struct, not a module

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `backend`.

To learn more, run the command again with --verbose.
```

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

The following patch enables the workaround, described above by pinning the downgraded version in `Cargo.toml`:

```patch
diff --git a/Backend/Cargo.toml b/Backend/Cargo.toml
index 35ffe77..4568d61 100644
--- a/Backend/Cargo.toml
+++ b/Backend/Cargo.toml
@@ -28,7 +28,7 @@ lazy_static = "*"
 regex = "*"
 dotenv = "*"
 byteorder="*"
-rocket-multipart-form-data="*"
+rocket-multipart-form-data="0.8.1"
 
 [dependencies.rocket_contrib]
 version = "*"
```

**Comment by Geigerkind** [comment]
Fixed :)
